services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/htdocs/app/static
      - media_volume:/htdocs/app/media
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgres_data:
  static_volume:
  media_volume: